// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/skills": {
    params: {};
  };
  "/skill/:id": {
    params: {
      "id": string;
    };
  };
  "/submit": {
    params: {};
  };
  "/profile/:address": {
    params: {
      "address": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/skills" | "/skill/:id" | "/submit" | "/profile/:address";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/skills.tsx": {
    id: "routes/skills";
    page: "/skills";
  };
  "routes/skill-detail.tsx": {
    id: "routes/skill-detail";
    page: "/skill/:id";
  };
  "routes/submit.tsx": {
    id: "routes/submit";
    page: "/submit";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile/:address";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/skills": typeof import("./app/routes/skills.tsx");
  "routes/skill-detail": typeof import("./app/routes/skill-detail.tsx");
  "routes/submit": typeof import("./app/routes/submit.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
};